version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp appspec.yml build
      - cp -r scripts build
artifacts:
  files:
    - build/**/*